# -*- coding: utf-8 mode: yaml -*- vim:sw=4:sts=4:et:ai:si:sta:fenc=utf-8

services:
  #db:
  #  build: &build-db
  #    context: .
  #    dockerfile: Dockerfile.db
  #    args:
  #      PRIVAREG: ${PRIVAREG:-docker.io}/
  #  environment: &environment-db
  #    DEVEL: 1
  #  volumes:
  #    - db-data:/var/lib/mysql
  #    - ./_db/sqlmig:/mariadb-config/sqlmig
  #  networks:
  #    default:
  #      aliases:
  #        - pv-jurydb
  #
  #adminer:
  #  build: &build-adminer
  #    context: .
  #    dockerfile: Dockerfile.adminer
  #    args:
  #      PRIVAREG: ${PRIVAREG:-docker.io}/
  #  environment: &environment-adminer
  #    DBHOST: pv-jurydb
  #    DBAUTO: admin/admin@pv_jury

  web:
    build: &build-web
      context: .
      dockerfile: Dockerfile.web
      args:
        PRIVAREG: ${PRIVAREG:-docker.io}/
        XDEBUG: 1
    environment: &environment-web
      #<<: *environment-adminer
      DEVEL: 1
      DEVUSER_USERENT: ${DEVUSER_USERENT:-}
      DEVUSER_GROUPENT: ${DEVUSER_GROUPENT:-}
      APACHE_DEVUSER: 1
      APP_PROFILE: devel
      BASE_URL: http://localhost:7081
      AUTH_CAS: $AUTH_CAS
      CAS_URL: $CAS_URL
      PV_JURY_DATADIR: /data/pv-jury
      TAIL_LOGFILES: >
        /data/pv-jury/log/pv-jury*.log
      LOGROTATE_STATEFILE: /data/pv-jury/logrotate.state
    volumes: &volumes-web
      - session-data:/var/lib/php/sessions
      - .:/var/www/app
      - ./devel:/data/pv-jury
      # cf la clé "require" dans composer.json
    ports:
      - 7081:80
      #- 7444:443
    extra_hosts:
      - "smtp.univ.run:10.82.70.46"

  cron:
    build: *build-web
    environment:
      <<: *environment-web
      TAIL_LOGFILES: >
        /data/pv-jury/log/cron*.log
    command: cron
    volumes: *volumes-web
    healthcheck:
      disable: true

volumes:
  #db-data:
  session-data:

networks:
  default:
