# -*- coding: utf-8 mode: yaml -*- vim:sw=4:sts=4:et:ai:si:sta:fenc=utf-8

services:
  web:
    build: &build-web
      context: .
      args:
        PRIVAREG: ${PRIVAREG:-docker.io}/
        XDEBUG: 1
    environment: &environment-web
      PROD: 1
      APP_PROFILE: prod
      BASE_URL: $APP_URL
      AUTH_CAS: $AUTH_CAS
      CAS_URL: $CAS_URL
      PV_JURY_DATADIR: /data/pv-jury
      TAIL_LOGFILES: >
        /data/pv-jury/log/pv-jury*.log
      LOGROTATE_STATEFILE: /data/pv-jury/logrotate.state
    volumes: &volumes-web
      - session-data:/var/lib/php/sessions
      - app-data:/data/pv-jury
      - .:/var/www/app
    ports:
      - ${LSN_ADDR}:80
    restart: always

  cron:
    build: *build-web
    environment:
      <<: *environment-web
      TAIL_LOGFILES: >
        /data/pv-jury/log/cron*.log
    command: cron
    volumes: *volumes-web
    healthcheck:
      disable: true

volumes:
  session-data:
  app-data:

networks:
  default:
