#!/bin/bash
# -*- coding: utf-8 mode: sh -*- vim:sw=4:sts=4:et:ai:si:sta:fenc=utf-8
MYDIR="$(cd "$(dirname -- "$0")"; pwd)"
"$MYDIR/sbin/runphp" --bs --ue --ci || exit 1
PVJURY="$MYDIR"
source "$PVJURY/vendor/nulib/base/load.sh" || exit 1

function dclsct() {
    # afficher les containers correspondant à $@ (docker-compose.yml)
    local composefile; local -a composeargs
    for composefile in "$@"; do
        [ -n "$composefile" ] || continue
        composeargs+=(-f "$composefile")
    done
    docker compose "${composeargs[@]}" ps -q
}

function dcrunning() {
    # vérifier si les containers correspondant à $@ (docker-compose.yml) tournent
    # si le premier argument est "-c count", c'est le nombre de service qui doit
    # tourner
    local count
    if [ "$1" == -c ]; then
        count="$2"; shift; shift
    elif [[ "$1" == -c* ]]; then
        count="${1#-c}"; shift
    fi
    if [ -n "$count" ]; then
        [ "$(dclsct "$@" | wc -l)" -eq "$count" ]
    else
        [ -n "$(dclsct "$@")" ]
    fi
}

function _set_composefiles() {
    composefile="$PVJURY/docker-compose.yml"
    composefiles=("$composefile")
    composeargs=(-f "$composefile")
    for localfile in override local; do
        localfile="$PVJURY/docker-compose.$localfile.yml"
        if [ -f "$localfile" ]; then
            composefiles+=("$localfile")
            composeargs+=(-f "$localfile")
        fi
    done
}

function start_pvjury() {
    local composefile localfile; local -a composefiles composeargs
    _set_composefiles

    [ -f "$composefile" ] || die "$composefile: fichier introuvable"
    if [ -n "$ForceStart" ]; then
        :
    elif dcrunning "${composefiles[@]}"; then
        enote "L'application PV-Jury est démarrée"
        return
    fi

    if [ -n "$Rebuild" ]; then
        "$MYDIR/sbin/build" -r || die
    fi

    estep "Démarrage de l'application PV-Jury"
    docker compose "${composeargs[@]}" up -d --wait --build ${Recreate:+--force-recreate} || die

    if [ -n "$Devel" ]; then
        auto_down=1
        function auto_down_trap() {
            if [ -n "$auto_down" ]; then
                docker compose "${composeargs[@]}" down
            fi
        }
        trap auto_down_trap 1 3 15 EXIT

        docker compose "${composeargs[@]}" logs -f
    fi
}

function stop_pvjury() {
    local composefile localfile; local -a composefiles composeargs
    _set_composefiles

    [ -f "$composefile" ] || return 0
    if dcrunning "${composefiles[@]}"; then
        estep "Arrêt de l'application PV-Jury"
        docker compose "${composeargs[@]}" down || die
    fi
}

function refresh_pvjury() {
    local ForceStart=1 Recreate=
    start_pvjury "$@"
}

function restart_pvjury() {
    local ForceStart=1 Recreate=1
    start_pvjury "$@"
}

function shell_prompt() {
     local composefile localfile; local -a composefiles composeargs
    _set_composefiles

    [ -f "$composefile" ] || die "$composefile: fichier introuvable"
    if dcrunning "${composefiles[@]}"; then
        local container="$1"; shift
        local -a cmd
        if [ $# -gt 0 ]; then
            cmd=("$@")
            estep "$container $1"
        else
            cmd=(bash)
            estep "$container Invite shell"
        fi
        docker compose "${composeargs[@]}" exec "$container" "${cmd[@]}" || die
    else
        eerror "Impossible de lancer l'invite shell $container: l'application PV-Jury est arrêtée"
    fi
}

action=start
Rebuild=
Devel=
args=(
    "Contrôler l'application PV-Jury"
    -s,--start action=start "Démarrer l'application si elle ne tourne pas déjà"
    -k,--stop action=stop "Arrêter l'application"
    -r,--refresh action=refresh "Redémarrer l'application si nécessaire"
    -R,--restart action=restart "Forcer l'arrêt puis le démarrage de l'application"
    -b,-B,--rebuild Rebuild=1 "++Forcer la (re)construction des images avant le démarrage"
    -D,--devel Devel=1 "++Activer le mode développement (start + log + autodown)"
    -x,--shell-web action=shell_web "Lancer une invite bash dans le container web"
    --shell-cron action=shell_cron "Lancer une invite bash dans le container cron"
)
parse_args "$@"; set -- "${args[@]}"

case "$action" in
start) start_pvjury "$@";;
stop) stop_pvjury "$@";;
refresh) refresh_pvjury "$@";;
restart) restart_pvjury "$@";;
shell_*) shell_prompt "${action#shell_}" "$@";;
*) die "$action: action non implémentée";;
esac
