# -*- coding: utf-8 mode: yaml -*- vim:sw=2:sts=2:et:ai:si:sta:fenc=utf-8

services:
  web:
    networks:
      demolb:
    ports: !override []
    labels:
      - "traefik.http.routers.http-pv-jury-web.entryPoints=http"
      - "traefik.http.routers.http-pv-jury-web.rule=Host(`pv-jury.demo.jclain.fr`)"
      - "traefik.http.routers.http-pv-jury-web.middlewares=redir2https@file"
      - "traefik.http.routers.http-pv-jury-web.service=pv-jury-web"
      - "traefik.http.routers.https-pv-jury-web.entryPoints=https"
      - "traefik.http.routers.https-pv-jury-web.rule=Host(`pv-jury.demo.jclain.fr`)"
      - "traefik.http.routers.https-pv-jury-web.tls=true"
      - "traefik.http.routers.https-pv-jury-web.tls.certresolver=le"
      - "traefik.http.routers.https-pv-jury-web.service=pv-jury-web"
      - "traefik.enable=true"
      - "traefik.http.services.pv-jury-web.loadbalancer.server.port=80"

networks:
  demolb:
    external: true
